language: cpp
script:
- cat /etc/lsb-release &&
  echo TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} &&
  echo TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER} &&
  echo TRAVIS_BRANCH=${TRAVIS_BRANCH} &&
  echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} &&
  echo SHELL=$SHELL
- ./build_scripts/travis/build-scroom
sudo: required
dist: trusty
compiler:
- clang
- gcc
env:
- NONE=""
- DISTCHECK_CONFIGURE_FLAGS='--enable-debug-tiles --disable-multithreading CFLAGS="-g -O0" CXXFLAGS="-g -O0"' LDFLAGS="-Wl,-z,defs"
- SOME_DISTS="trusty xenial precise" OTHER_DISTS="yakkety vivid wily"
addons:
  apt:
    packages:
    - libboost-test-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libcairo2-dev
    - libglade2-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libtiff5-dev
    - pkg-config
    - doxygen
    - graphviz
before_install:
- openssl aes-256-cbc -K $encrypted_59cb415a9a11_key -iv $encrypted_59cb415a9a11_iv
  -in build_scripts/travis/config/travisci_rsa.enc -out build_scripts/travis/config/travisci_rsa -d
- chmod 0600 build_scripts/travis/config/travisci_rsa
- cp build_scripts/travis/config/travisci_rsa ~/.ssh/id_rsa
git:
  depth: 200
  