Scroom: PresentationBase Class Reference
PresentationBase Class Reference abstract
#include <presentationinterface.hh>
Public Member Functions
void open (ViewInterface::WeakPtr vi) override
void close (ViewInterface::WeakPtr vi) override
void showMetadata () override
Public Member Functions inherited from PresentationInterface
virtual Scroom::Utils::Rectangle< double > getRect ()=0
virtual void redraw (ViewInterface::Ptr const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom)=0
virtual bool getProperty (const std::string &name, std::string &value)=0
virtual bool isPropertyDefined (const std::string &name)=0
virtual std::string getTitle ()=0
virtual Scroom::Utils::Point< double > getAspectRatio () const
Public Member Functions inherited from Scroom::Utils::Observable< T >
Observable ()
~Observable () override
Observable (const Observable &)=delete
Observable (Observable &&)=delete
Observable operator= (const Observable &)=delete
Observable operator= (Observable &&)=delete
Scroom::Bookkeeping::Token registerStrongObserver (Observer const &observer)
Scroom::Bookkeeping::Token registerObserver (ObserverWeak const &observer)
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Protected Member Functions
void observerAdded (Viewable::Ptr const &viewable, Scroom::Bookkeeping::Token const &t) override
virtual void viewAdded (ViewInterface::WeakPtr vi)=0
virtual void viewRemoved (ViewInterface::WeakPtr vi)=0
virtual std::set< ViewInterface::WeakPtr > getViews ()=0
Protected Member Functions inherited from Scroom::Utils::Observable< T >
std::list< Observer > getObservers ()
virtual void observerAdded (Observer const &observer, Scroom::Bookkeeping::Token const &token)
Additional Inherited Members
Public Types inherited from PresentationInterface
using Ptr = boost::shared_ptr< PresentationInterface >
using WeakPtr = boost::weak_ptr< PresentationInterface >
Public Types inherited from Viewable
using Ptr = boost::shared_ptr< Viewable >
using WeakPtr = boost::weak_ptr< Viewable >
Public Types inherited from Scroom::Utils::Observable< T >
using Observer = boost::shared_ptr< T >
using Ptr = boost::shared_ptr< Observable< T > >
Public Types inherited from MetadataViewInterface
using Ptr = boost::shared_ptr< MetadataViewInterface >
Member Function Documentation
close()
void PresentationBase::close (ViewInterface::WeakPtr vi) override virtual
Gets called just before the View is destroyed
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Reimplemented in TransformPresentation.
 {
   std::list<Viewable::Ptr> const observers = getObservers();
   for(Viewable::Ptr const& observer: observers)
   {
     observer->close(vi);
   }
   viewRemoved(vi);
 }
Referenced by TransformPresentation::close().
getViews()
virtual std::set<ViewInterface::WeakPtr> PresentationBase::getViews () protected pure virtual
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransparentOverlayPresentation, and PresentationBaseSimple.
Referenced by observerAdded().
observerAdded()
void PresentationBase::observerAdded (Viewable::Ptr const & viewable, Scroom::Bookkeeping::Token const & t) override protected
 {
   std::set<ViewInterface::WeakPtr> views = getViews();
   for(ViewInterface::WeakPtr const& view: views)
   {
     viewable->open(view);
   }
 }
open()
void PresentationBase::open (ViewInterface::WeakPtr vi) override virtual
Gets called just after the View is created
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Reimplemented in TransformPresentation.
 {
   viewAdded(vi);
   std::list<Viewable::Ptr> const observers = getObservers();
   for(Viewable::Ptr const& observer: observers)
   {
     observer->open(vi);
   }
 }
Referenced by TransformPresentation::open().
showMetadata()
void PresentationBase::showMetadata () override virtual
Show image metadata of the current presentation
Base method that shows image metadata window for unimplemented presentations on which the user clicks the metadata button.
Implements MetadataViewInterface.
Reimplemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, and TransformPresentation.
 {
   GtkWidget*  dialog;
   GtkWidget*  label;
   GtkBuilder* builder;
   GtkWidget*  box;
   builder = gtk_builder_new();
   gtk_builder_add_from_file(builder, "popup.builder", NULL);
   printf("Creating the properties window.\n");
   // create top level window and set its size
   dialog = gtk_window_new(GTK_WINDOW_TOPLEVEL);
   gtk_window_set_title(GTK_WINDOW(dialog), "Properties");
   gtk_window_set_decorated(GTK_WINDOW(dialog), TRUE);
   gtk_window_set_position(GTK_WINDOW(dialog), GTK_WIN_POS_CENTER);
   gtk_window_set_default_size(GTK_WINDOW(dialog), 400, 300);
   gtk_builder_connect_signals(builder, dialog);
   g_object_unref(G_OBJECT(builder));
   // create label in window and paste it in container
   label = gtk_label_new("NOT IMPLEMENTED FOR THIS PRESENTATION");
   box   = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
   gtk_box_pack_start(GTK_BOX(box), label, true, false, 5);
   gtk_container_add(GTK_CONTAINER(dialog), box);
   // show widgets in window dialog
   gtk_widget_show_all(dialog);
   gtk_widget_grab_focus(dialog);
 }
viewAdded()
virtual void PresentationBase::viewAdded (ViewInterface::WeakPtr vi) protected pure virtual
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransparentOverlayPresentation, and PresentationBaseSimple.
Referenced by open().
viewRemoved()
virtual void PresentationBase::viewRemoved (ViewInterface::WeakPtr vi) protected pure virtual
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransparentOverlayPresentation, and PresentationBaseSimple.
Referenced by close().
The documentation for this class was generated from the following files:
inc/scroom/presentationinterface.hh
libs/scroom/src/presentationinterface.cc